//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hcsn.WebApplication.Common.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hcsn.WebApplication.Common.Resource.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cost.
        /// </summary>
        public static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cost.
        /// </summary>
        public static string CostPropName {
            get {
                return ResourceManager.GetString("CostPropName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to depreciation_rate.
        /// </summary>
        public static string DepreciationRatePropName {
            get {
                return ResourceManager.GetString("DepreciationRatePropName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fixed_asset_category_code.
        /// </summary>
        public static string FixedAssetCategoryCodePropName {
            get {
                return ResourceManager.GetString("FixedAssetCategoryCodePropName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fixed_asset_category_id.
        /// </summary>
        public static string FixedAssetCategoryIdPropName {
            get {
                return ResourceManager.GetString("FixedAssetCategoryIdPropName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fixed_asset_category_name.
        /// </summary>
        public static string FixedAssetCategoryNamePropName {
            get {
                return ResourceManager.GetString("FixedAssetCategoryNamePropName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fixed_asset_code.
        /// </summary>
        public static string FixedAssetCodePropName {
            get {
                return ResourceManager.GetString("FixedAssetCodePropName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fixed_asset_id.
        /// </summary>
        public static string FixedAssetIdPropName {
            get {
                return ResourceManager.GetString("FixedAssetIdPropName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to voucher_code.
        /// </summary>
        public static string FixedAssetIncrementCodePropName {
            get {
                return ResourceManager.GetString("FixedAssetIncrementCodePropName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fixed_asset_name.
        /// </summary>
        public static string FixedAssetNamePropName {
            get {
                return ResourceManager.GetString("FixedAssetNamePropName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng cộng.
        /// </summary>
        public static string FooterTableExcelTotal {
            get {
                return ResourceManager.GetString("FooterTableExcelTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to life_time.
        /// </summary>
        public static string LifeTimePropName {
            get {
                return ResourceManager.GetString("LifeTimePropName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TS00001.
        /// </summary>
        public static string NewAssetCodeDefault {
            get {
                return ResourceManager.GetString("NewAssetCodeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GT00001.
        /// </summary>
        public static string NewVoucherCodeDefault {
            get {
                return ResourceManager.GetString("NewVoucherCodeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to production_year.
        /// </summary>
        public static string ProductionYear {
            get {
                return ResourceManager.GetString("ProductionYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quantity.
        /// </summary>
        public static string QuantityPropName {
            get {
                return ResourceManager.GetString("QuantityPropName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chứng từ chi tiết.
        /// </summary>
        public static string TableExcelAssetIncrementDetailSheetName {
            get {
                return ResourceManager.GetString("TableExcelAssetIncrementDetailSheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin chi tiêt.
        /// </summary>
        public static string TableExcelAssetIncrementDetailTitleAsset {
            get {
                return ResourceManager.GetString("TableExcelAssetIncrementDetailTitleAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin chứng từ.
        /// </summary>
        public static string TableExcelAssetIncrementDetailTitleAssetIncrement {
            get {
                return ResourceManager.GetString("TableExcelAssetIncrementDetailTitleAssetIncrement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chứng từ.
        /// </summary>
        public static string TableExcelAssetIncrementSheetName {
            get {
                return ResourceManager.GetString("TableExcelAssetIncrementSheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách chứng từ.
        /// </summary>
        public static string TableExcelAssetIncrementTitle {
            get {
                return ResourceManager.GetString("TableExcelAssetIncrementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài sản.
        /// </summary>
        public static string TableExcelAssetSheetName {
            get {
                return ResourceManager.GetString("TableExcelAssetSheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách tài sản.
        /// </summary>
        public static string TableExcelAssetTitle {
            get {
                return ResourceManager.GetString("TableExcelAssetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại tài sản.
        /// </summary>
        public static string TableExcelHeaderColumnAssetCategory {
            get {
                return ResourceManager.GetString("TableExcelHeaderColumnAssetCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã tài sản.
        /// </summary>
        public static string TableExcelHeaderColumnAssetCode {
            get {
                return ResourceManager.GetString("TableExcelHeaderColumnAssetCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tài sản.
        /// </summary>
        public static string TableExcelHeaderColumnAssetName {
            get {
                return ResourceManager.GetString("TableExcelHeaderColumnAssetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nguyên giá.
        /// </summary>
        public static string TableExcelHeaderColumnCost {
            get {
                return ResourceManager.GetString("TableExcelHeaderColumnCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bộ phận sử dụng.
        /// </summary>
        public static string TableExcelHeaderColumnDepartment {
            get {
                return ResourceManager.GetString("TableExcelHeaderColumnDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HM/KH lũy kế.
        /// </summary>
        public static string TableExcelHeaderColumnDepreciationValue {
            get {
                return ResourceManager.GetString("TableExcelHeaderColumnDepreciationValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung.
        /// </summary>
        public static string TableExcelHeaderColumnDescription {
            get {
                return ResourceManager.GetString("TableExcelHeaderColumnDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày ghi tăng.
        /// </summary>
        public static string TableExcelHeaderColumnIncrementDate {
            get {
                return ResourceManager.GetString("TableExcelHeaderColumnIncrementDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STT.
        /// </summary>
        public static string TableExcelHeaderColumnIndex {
            get {
                return ResourceManager.GetString("TableExcelHeaderColumnIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng nguyên giá.
        /// </summary>
        public static string TableExcelHeaderColumnPrice {
            get {
                return ResourceManager.GetString("TableExcelHeaderColumnPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng.
        /// </summary>
        public static string TableExcelHeaderColumnQuantity {
            get {
                return ResourceManager.GetString("TableExcelHeaderColumnQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị còn lại.
        /// </summary>
        public static string TableExcelHeaderColumnResidualValue {
            get {
                return ResourceManager.GetString("TableExcelHeaderColumnResidualValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã chứng từ.
        /// </summary>
        public static string TableExcelHeaderColumnVoucherCode {
            get {
                return ResourceManager.GetString("TableExcelHeaderColumnVoucherCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày chứng từ.
        /// </summary>
        public static string TableExcelHeaderColumnVoucherDate {
            get {
                return ResourceManager.GetString("TableExcelHeaderColumnVoucherDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy dữ liệu phù hợp. Vui lòng kiểm tra lại!.
        /// </summary>
        public static string TableExcelNoData {
            get {
                return ResourceManager.GetString("TableExcelNoData", resourceCulture);
            }
        }
    }
}
