//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hcsn.WebApplication.Common.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hcsn.WebApplication.Common.Resource.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng cộng.
        /// </summary>
        public static string FooterTableExcelTotal {
            get {
                return ResourceManager.GetString("FooterTableExcelTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TS00001.
        /// </summary>
        public static string NewCodeDefault {
            get {
                return ResourceManager.GetString("NewCodeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại tài sản.
        /// </summary>
        public static string TableExcelHeaderColumnAssetCategory {
            get {
                return ResourceManager.GetString("TableExcelHeaderColumnAssetCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã tài sản.
        /// </summary>
        public static string TableExcelHeaderColumnAssetCode {
            get {
                return ResourceManager.GetString("TableExcelHeaderColumnAssetCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tài sản.
        /// </summary>
        public static string TableExcelHeaderColumnAssetName {
            get {
                return ResourceManager.GetString("TableExcelHeaderColumnAssetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nguyên giá.
        /// </summary>
        public static string TableExcelHeaderColumnCost {
            get {
                return ResourceManager.GetString("TableExcelHeaderColumnCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bộ phận sử dụng.
        /// </summary>
        public static string TableExcelHeaderColumnDepartment {
            get {
                return ResourceManager.GetString("TableExcelHeaderColumnDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HM/KH lũy kế.
        /// </summary>
        public static string TableExcelHeaderColumnDepreciationValue {
            get {
                return ResourceManager.GetString("TableExcelHeaderColumnDepreciationValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STT.
        /// </summary>
        public static string TableExcelHeaderColumnIndex {
            get {
                return ResourceManager.GetString("TableExcelHeaderColumnIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng.
        /// </summary>
        public static string TableExcelHeaderColumnQuantity {
            get {
                return ResourceManager.GetString("TableExcelHeaderColumnQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị còn lại.
        /// </summary>
        public static string TableExcelHeaderColumnResidualValue {
            get {
                return ResourceManager.GetString("TableExcelHeaderColumnResidualValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets.
        /// </summary>
        public static string TableExcelSheetName {
            get {
                return ResourceManager.GetString("TableExcelSheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách tài sản.
        /// </summary>
        public static string TableExcelTitle {
            get {
                return ResourceManager.GetString("TableExcelTitle", resourceCulture);
            }
        }
    }
}
